"""
Sample ecommerce product catalog.
Each product has a text description (for vector search)
and structured metadata (for hard filtering).
"""

PRODUCTS = [
    # ── Headphones (noise cancelling, various colors/prices) ──────────────────
    {
        "id": "p001",
        "description": "Sony WH-1000XM5 wireless over-ear headphones with industry-leading noise cancellation, 30-hour battery life, and multipoint connection.",
        "metadata": {
            "brand": "Sony",
            "product": "headphones",
            "feature": "noise cancelling,wireless",
            "color": "black",
            "price": 349.99,
            "rating": 4.8,
            "category": "electronics",
        },
    },
    {
        "id": "p002",
        "description": "Bose QuietComfort 45 noise cancelling headphones with high-fidelity audio, comfortable fit, and 24-hour battery.",
        "metadata": {
            "brand": "Bose",
            "product": "headphones",
            "feature": "noise cancelling,wireless",
            "color": "white",
            "price": 279.00,
            "rating": 4.7,
            "category": "electronics",
        },
    },
    {
        "id": "p003",
        "description": "Bose QuietComfort 35 II noise cancelling wireless headphones in silver, with Alexa voice control and 20-hour battery.",
        "metadata": {
            "brand": "Bose",
            "product": "headphones",
            "feature": "noise cancelling,wireless,voice control",
            "color": "silver",
            "price": 199.00,
            "rating": 4.7,
            "category": "electronics",
        },
    },
    {
        "id": "p004",
        "description": "Anker Soundcore Q20 budget wireless headphones with hybrid active noise cancellation and 40-hour playtime — great value under $60.",
        "metadata": {
            "brand": "Anker",
            "product": "headphones",
            "feature": "noise cancelling,wireless",
            "color": "black",
            "price": 59.99,
            "rating": 4.4,
            "category": "electronics",
        },
    },
    {
        "id": "p005",
        "description": "JBL Tune 760NC lightweight foldable noise cancelling headphones with 35-hour battery and JBL Pure Bass Sound.",
        "metadata": {
            "brand": "JBL",
            "product": "headphones",
            "feature": "noise cancelling,wireless,foldable",
            "color": "blue",
            "price": 99.95,
            "rating": 4.3,
            "category": "electronics",
        },
    },
    {
        "id": "p006",
        "description": "JBL Tune 510BT on-ear wireless headphones with 40-hour playtime and hands-free calling — available in white.",
        "metadata": {
            "brand": "JBL",
            "product": "headphones",
            "feature": "wireless,hands-free",
            "color": "white",
            "price": 49.95,
            "rating": 4.3,
            "category": "electronics",
        },
    },
    {
        "id": "p007",
        "description": "Sennheiser HD 560S open-back over-ear audiophile headphones for natural, reference-grade wired listening.",
        "metadata": {
            "brand": "Sennheiser",
            "product": "headphones",
            "feature": "wired,open-back,audiophile",
            "color": "black",
            "price": 199.95,
            "rating": 4.6,
            "category": "electronics",
        },
    },
    {
        "id": "p008",
        "description": "Beats Studio Pro wireless noise cancelling headphones with personalized spatial audio, USB-C, and 40-hour battery — in navy.",
        "metadata": {
            "brand": "Beats",
            "product": "headphones",
            "feature": "noise cancelling,wireless,spatial audio",
            "color": "navy",
            "price": 179.95,
            "rating": 4.4,
            "category": "electronics",
        },
    },
    {
        "id": "p009",
        "description": "Jabra Evolve2 85 professional wireless headphones with dual-hybrid ANC, meeting-optimized microphones, and all-day comfort.",
        "metadata": {
            "brand": "Jabra",
            "product": "headphones",
            "feature": "noise cancelling,wireless,professional",
            "color": "black",
            "price": 379.00,
            "rating": 4.6,
            "category": "electronics",
        },
    },
    {
        "id": "p010",
        "description": "Sony WH-CH720N lightweight noise cancelling headphones with up to 35-hour battery and multipoint connection — in white.",
        "metadata": {
            "brand": "Sony",
            "product": "headphones",
            "feature": "noise cancelling,wireless",
            "color": "white",
            "price": 149.99,
            "rating": 4.5,
            "category": "electronics",
        },
    },
    {
        "id": "p011",
        "description": "Sony WH-CH720N noise cancelling headphones — same great model, available in blue for a splash of color.",
        "metadata": {
            "brand": "Sony",
            "product": "headphones",
            "feature": "noise cancelling,wireless",
            "color": "blue",
            "price": 149.99,
            "rating": 4.5,
            "category": "electronics",
        },
    },
    {
        "id": "p012",
        "description": "Anker Soundcore Life Q35 multi-mode active noise cancelling headphones with LDAC hi-res audio and 40-hour battery — in blue.",
        "metadata": {
            "brand": "Anker",
            "product": "headphones",
            "feature": "noise cancelling,wireless,hi-res audio",
            "color": "blue",
            "price": 79.99,
            "rating": 4.5,
            "category": "electronics",
        },
    },
    {
        "id": "p013",
        "description": "Technics EAH-A800 premium wireless noise cancelling headphones with multipoint Bluetooth, 50-hour battery, and refined design — in silver.",
        "metadata": {
            "brand": "Technics",
            "product": "headphones",
            "feature": "noise cancelling,wireless,hi-res audio",
            "color": "silver",
            "price": 199.99,
            "rating": 4.7,
            "category": "electronics",
        },
    },
    # ── Earbuds ───────────────────────────────────────────────────────────────
    {
        "id": "p014",
        "description": "Apple AirPods Pro (2nd Gen) in-ear earbuds with active noise cancellation, adaptive transparency, and MagSafe charging case.",
        "metadata": {
            "brand": "Apple",
            "product": "earbuds",
            "feature": "noise cancelling,wireless",
            "color": "white",
            "price": 249.00,
            "rating": 4.9,
            "category": "electronics",
        },
    },
    {
        "id": "p015",
        "description": "Samsung Galaxy Buds2 Pro true wireless earbuds with intelligent ANC, 360-degree audio, and IPX7 water resistance.",
        "metadata": {
            "brand": "Samsung",
            "product": "earbuds",
            "feature": "noise cancelling,wireless,waterproof",
            "color": "graphite",
            "price": 199.99,
            "rating": 4.5,
            "category": "electronics",
        },
    },
    {
        "id": "p016",
        "description": "Sony WF-1000XM4 true wireless earbuds with best-in-class noise cancellation, LDAC hi-res audio, and IPX4 splash resistance — in black.",
        "metadata": {
            "brand": "Sony",
            "product": "earbuds",
            "feature": "noise cancelling,wireless,hi-res audio",
            "color": "black",
            "price": 278.00,
            "rating": 4.7,
            "category": "electronics",
        },
    },
    {
        "id": "p017",
        "description": "Sony WF-1000XM5 true wireless earbuds with next-generation noise cancellation, LDAC hi-res audio, and crystal-clear call quality — in silver.",
        "metadata": {
            "brand": "Sony",
            "product": "earbuds",
            "feature": "noise cancelling,wireless,hi-res audio",
            "color": "silver",
            "price": 299.99,
            "rating": 4.8,
            "category": "electronics",
        },
    },
    {
        "id": "p018",
        "description": "Sony LinkBuds S truly wireless noise cancelling earbuds with ultra-compact design, LDAC hi-res audio, and all-day comfort — in white.",
        "metadata": {
            "brand": "Sony",
            "product": "earbuds",
            "feature": "noise cancelling,wireless,hi-res audio,compact",
            "color": "white",
            "price": 148.00,
            "rating": 4.5,
            "category": "electronics",
        },
    },
    {
        "id": "p019",
        "description": "Jabra Elite 4 active noise cancelling true wireless earbuds with IP57 rating, 28-hour total battery, and multipoint connection.",
        "metadata": {
            "brand": "Jabra",
            "product": "earbuds",
            "feature": "noise cancelling,wireless,waterproof",
            "color": "navy",
            "price": 89.99,
            "rating": 4.4,
            "category": "electronics",
        },
    },
    {
        "id": "p020",
        "description": "Soundcore Liberty 4 NC true wireless earbuds with 98.5% noise cancellation, LDAC hi-res audio, and 50-hour total battery — in white.",
        "metadata": {
            "brand": "Anker",
            "product": "earbuds",
            "feature": "noise cancelling,wireless,hi-res audio",
            "color": "white",
            "price": 79.99,
            "rating": 4.5,
            "category": "electronics",
        },
    },
    # ── Laptops ───────────────────────────────────────────────────────────────
    {
        "id": "p021",
        "description": "Apple MacBook Air M3 13-inch ultralight laptop with 18-hour battery, Liquid Retina display, and silent fanless design.",
        "metadata": {
            "brand": "Apple",
            "product": "laptop",
            "feature": "lightweight,long battery,fanless",
            "color": "silver",
            "price": 1099.00,
            "rating": 4.9,
            "category": "computers",
        },
    },
    {
        "id": "p022",
        "description": "Dell XPS 15 OLED laptop with Intel Core i9, 32GB RAM, 1TB SSD, and a 3.5K OLED touch display for creators.",
        "metadata": {
            "brand": "Dell",
            "product": "laptop",
            "feature": "OLED display,high performance,creator",
            "color": "black",
            "price": 2199.00,
            "rating": 4.7,
            "category": "computers",
        },
    },
    {
        "id": "p023",
        "description": "Acer Aspire 3 budget laptop with AMD Ryzen 5, 8GB RAM, 512GB SSD — great everyday performance at an accessible price.",
        "metadata": {
            "brand": "Acer",
            "product": "laptop",
            "feature": "budget,everyday use",
            "color": "silver",
            "price": 399.99,
            "rating": 4.2,
            "category": "computers",
        },
    },
    {
        "id": "p024",
        "description": "HP 15 budget laptop with Intel Core i5, 8GB RAM, 256GB SSD, and Windows 11 — reliable and affordable for students.",
        "metadata": {
            "brand": "HP",
            "product": "laptop",
            "feature": "budget,student,everyday use",
            "color": "silver",
            "price": 449.00,
            "rating": 4.1,
            "category": "computers",
        },
    },
    {
        "id": "p025",
        "description": "Lenovo IdeaPad 3 budget laptop with AMD Ryzen 3, 8GB RAM, and 15.6-inch FHD display — a no-frills daily driver.",
        "metadata": {
            "brand": "Lenovo",
            "product": "laptop",
            "feature": "budget,everyday use",
            "color": "grey",
            "price": 369.00,
            "rating": 4.0,
            "category": "computers",
        },
    },
    {
        "id": "p026",
        "description": "ASUS VivoBook 15 slim laptop with Intel Core i3, 8GB RAM, 512GB SSD, and fingerprint reader — lightweight and budget-friendly.",
        "metadata": {
            "brand": "ASUS",
            "product": "laptop",
            "feature": "budget,lightweight,everyday use",
            "color": "black",
            "price": 429.99,
            "rating": 4.2,
            "category": "computers",
        },
    },
    {
        "id": "p027",
        "description": "Microsoft Surface Laptop 5 with Intel Evo i5, 8GB RAM, 512GB SSD, and 13.5-inch PixelSense touchscreen — in platinum.",
        "metadata": {
            "brand": "Microsoft",
            "product": "laptop",
            "feature": "lightweight,touchscreen,premium",
            "color": "silver",
            "price": 999.99,
            "rating": 4.6,
            "category": "computers",
        },
    },
    {
        "id": "p028",
        "description": "ASUS ROG Zephyrus G14 gaming laptop with AMD Ryzen 9, RTX 4060, 16GB RAM, and 120Hz 1440p display — compact powerhouse.",
        "metadata": {
            "brand": "ASUS",
            "product": "laptop",
            "feature": "gaming,high performance,compact",
            "color": "white",
            "price": 1449.99,
            "rating": 4.8,
            "category": "computers",
        },
    },
    # ── Running shoes ─────────────────────────────────────────────────────────
    {
        "id": "p029",
        "description": "Nike Pegasus 41 road running shoes with ReactX foam cushioning, breathable mesh upper, and durable rubber outsole — in blue.",
        "metadata": {
            "brand": "Nike",
            "product": "running shoes",
            "feature": "cushioned,road running,breathable",
            "color": "blue",
            "price": 134.99,
            "rating": 4.6,
            "category": "footwear",
        },
    },
    {
        "id": "p030",
        "description": "Nike Air Zoom Pegasus 40 running shoes — trusted daily trainer with Zoom Air cushioning and engineered mesh upper — in black.",
        "metadata": {
            "brand": "Nike",
            "product": "running shoes",
            "feature": "cushioned,road running,zoom air",
            "color": "black",
            "price": 129.99,
            "rating": 4.5,
            "category": "footwear",
        },
    },
    {
        "id": "p031",
        "description": "Nike React Infinity Run Flyknit 4 running shoes designed to reduce injury, with extra cushioning and a stable ride — in white.",
        "metadata": {
            "brand": "Nike",
            "product": "running shoes",
            "feature": "cushioned,road running,injury prevention",
            "color": "white",
            "price": 159.99,
            "rating": 4.7,
            "category": "footwear",
        },
    },
    {
        "id": "p032",
        "description": "Nike Free RN 5.0 Next Nature flexible everyday running shoes with lightweight knit upper and natural motion feel — in blue.",
        "metadata": {
            "brand": "Nike",
            "product": "running shoes",
            "feature": "lightweight,road running,flexible",
            "color": "blue",
            "price": 89.99,
            "rating": 4.3,
            "category": "footwear",
        },
    },
    {
        "id": "p033",
        "description": "ASICS Gel-Nimbus 26 premium running shoes with maximum cushioning, gel technology, and wide toe box for long-distance comfort.",
        "metadata": {
            "brand": "ASICS",
            "product": "running shoes",
            "feature": "cushioned,road running,wide fit",
            "color": "white",
            "price": 159.95,
            "rating": 4.8,
            "category": "footwear",
        },
    },
    {
        "id": "p034",
        "description": "Adidas Ultraboost 24 running shoes with responsive Boost midsole, Primeknit upper, and Continental rubber outsole — in black.",
        "metadata": {
            "brand": "Adidas",
            "product": "running shoes",
            "feature": "cushioned,road running,responsive",
            "color": "black",
            "price": 189.99,
            "rating": 4.7,
            "category": "footwear",
        },
    },
    {
        "id": "p035",
        "description": "New Balance Fresh Foam X 1080v13 premium daily running shoes with ultra-cushioned midsole and engineered mesh upper — in blue.",
        "metadata": {
            "brand": "New Balance",
            "product": "running shoes",
            "feature": "cushioned,road running,premium",
            "color": "blue",
            "price": 164.99,
            "rating": 4.8,
            "category": "footwear",
        },
    },
    {
        "id": "p036",
        "description": "Hoka Clifton 9 everyday running shoes with signature thick midsole, lightweight upper, and Meta-Rocker geometry for a smooth ride.",
        "metadata": {
            "brand": "Hoka",
            "product": "running shoes",
            "feature": "cushioned,road running,lightweight",
            "color": "white",
            "price": 144.95,
            "rating": 4.8,
            "category": "footwear",
        },
    },
    # ── Smartwatches ──────────────────────────────────────────────────────────
    {
        "id": "p037",
        "description": "Apple Watch Series 9 with always-on Retina display, double tap gesture, ECG, crash detection, and 18-hour battery — in midnight.",
        "metadata": {
            "brand": "Apple",
            "product": "smartwatch",
            "feature": "ECG,crash detection,fitness tracking",
            "color": "black",
            "price": 399.00,
            "rating": 4.8,
            "category": "wearables",
        },
    },
    {
        "id": "p038",
        "description": "Samsung Galaxy Watch 6 with advanced sleep coaching, heart rate tracking, body composition analysis, and a sleek circular design.",
        "metadata": {
            "brand": "Samsung",
            "product": "smartwatch",
            "feature": "sleep tracking,fitness tracking,health monitoring",
            "color": "silver",
            "price": 299.99,
            "rating": 4.5,
            "category": "wearables",
        },
    },
    {
        "id": "p039",
        "description": "Garmin Forerunner 265 GPS running smartwatch with AMOLED display, training readiness score, and up to 15 days battery life.",
        "metadata": {
            "brand": "Garmin",
            "product": "smartwatch",
            "feature": "GPS,running,long battery,fitness tracking",
            "color": "black",
            "price": 449.99,
            "rating": 4.7,
            "category": "wearables",
        },
    },
    {
        "id": "p040",
        "description": "Fitbit Versa 4 fitness smartwatch with built-in GPS, 6-day battery, 40+ exercise modes, and Daily Readiness Score — in pink.",
        "metadata": {
            "brand": "Fitbit",
            "product": "smartwatch",
            "feature": "GPS,fitness tracking,long battery",
            "color": "pink",
            "price": 199.95,
            "rating": 4.3,
            "category": "wearables",
        },
    },
]
