"""
Sample ecommerce product catalog.
Each product has a text description (for vector search)
and structured metadata (for hard filtering).
"""

PRODUCTS = [
    # ── Headphones (noise cancelling, various colors/prices) ──────────────────
    {
        "id": "p001",
        "description": "Sony WH-1000XM5 wireless over-ear headphones with industry-leading noise cancellation, 30-hour battery life, and multipoint connection.",
        "metadata": {
            "brand": "Sony",
            "product": "headphones",
            "feature": "noise cancelling,wireless",
            "color": "black",
            "price": 349.99,
            "rating": 4.8,
            "category": "electronics",
        },
    },
    {
        "id": "p002",
        "description": "Bose QuietComfort 45 noise cancelling headphones with high-fidelity audio, comfortable fit, and 24-hour battery.",
        "metadata": {
            "brand": "Bose",
            "product": "headphones",
            "feature": "noise cancelling,wireless",
            "color": "white",
            "price": 279.00,
            "rating": 4.7,
            "category": "electronics",
        },
    },
    {
        "id": "p003",
        "description": "Bose QuietComfort 35 II noise cancelling wireless headphones in silver, with Alexa voice control and 20-hour battery.",
        "metadata": {
            "brand": "Bose",
            "product": "headphones",
            "feature": "noise cancelling,wireless,voice control",
            "color": "silver",
            "price": 199.00,
            "rating": 4.7,
            "category": "electronics",
        },
    },
    {
        "id": "p004",
        "description": "Anker Soundcore Q20 budget wireless headphones with hybrid active noise cancellation and 40-hour playtime — great value under $60.",
        "metadata": {
            "brand": "Anker",
            "product": "headphones",
            "feature": "noise cancelling,wireless",
            "color": "black",
            "price": 59.99,
            "rating": 4.4,
            "category": "electronics",
        },
    },
    {
        "id": "p005",
        "description": "JBL Tune 760NC lightweight foldable noise cancelling headphones with 35-hour battery and JBL Pure Bass Sound.",
        "metadata": {
            "brand": "JBL",
            "product": "headphones",
            "feature": "noise cancelling,wireless,foldable",
            "color": "blue",
            "price": 99.95,
            "rating": 4.3,
            "category": "electronics",
        },
    },
    {
        "id": "p006",
        "description": "JBL Tune 510BT on-ear wireless headphones with 40-hour playtime and hands-free calling — available in white.",
        "metadata": {
            "brand": "JBL",
            "product": "headphones",
            "feature": "wireless,hands-free",
            "color": "white",
            "price": 49.95,
            "rating": 4.3,
            "category": "electronics",
        },
    },
    {
        "id": "p007",
        "description": "Sennheiser HD 560S open-back over-ear audiophile headphones for natural, reference-grade wired listening.",
        "metadata": {
            "brand": "Sennheiser",
            "product": "headphones",
            "feature": "wired,open-back,audiophile",
            "color": "black",
            "price": 199.95,
            "rating": 4.6,
            "category": "electronics",
        },
    },
    {
        "id": "p008",
        "description": "Beats Studio Pro wireless noise cancelling headphones with personalized spatial audio, USB-C, and 40-hour battery — in navy.",
        "metadata": {
            "brand": "Beats",
            "product": "headphones",
            "feature": "noise cancelling,wireless,spatial audio",
            "color": "navy",
            "price": 179.95,
            "rating": 4.4,
            "category": "electronics",
        },
    },
    {
        "id": "p009",
        "description": "Jabra Evolve2 85 professional wireless headphones with dual-hybrid ANC, meeting-optimized microphones, and all-day comfort.",
        "metadata": {
            "brand": "Jabra",
            "product": "headphones",
            "feature": "noise cancelling,wireless,professional",
            "color": "black",
            "price": 379.00,
            "rating": 4.6,
            "category": "electronics",
        },
    },
    {
        "id": "p010",
        "description": "Sony WH-CH720N lightweight noise cancelling headphones with up to 35-hour battery and multipoint connection — in white.",
        "metadata": {
            "brand": "Sony",
            "product": "headphones",
            "feature": "noise cancelling,wireless",
            "color": "white",
            "price": 149.99,
            "rating": 4.5,
            "category": "electronics",
        },
    },
    {
        "id": "p011",
        "description": "Sony WH-CH720N noise cancelling headphones — same great model, available in blue for a splash of color.",
        "metadata": {
            "brand": "Sony",
            "product": "headphones",
            "feature": "noise cancelling,wireless",
            "color": "blue",
            "price": 149.99,
            "rating": 4.5,
            "category": "electronics",
        },
    },
    {
        "id": "p012",
        "description": "Anker Soundcore Life Q35 multi-mode active noise cancelling headphones with LDAC hi-res audio and 40-hour battery — in blue.",
        "metadata": {
            "brand": "Anker",
            "product": "headphones",
            "feature": "noise cancelling,wireless,hi-res audio",
            "color": "blue",
            "price": 79.99,
            "rating": 4.5,
            "category": "electronics",
        },
    },
    {
        "id": "p013",
        "description": "Technics EAH-A800 premium wireless noise cancelling headphones with multipoint Bluetooth, 50-hour battery, and refined design — in silver.",
        "metadata": {
            "brand": "Technics",
            "product": "headphones",
            "feature": "noise cancelling,wireless,hi-res audio",
            "color": "silver",
            "price": 199.99,
            "rating": 4.7,
            "category": "electronics",
        },
    },
    # ── Earbuds ───────────────────────────────────────────────────────────────
    {
        "id": "p014",
        "description": "Apple AirPods Pro (2nd Gen) in-ear earbuds with active noise cancellation, adaptive transparency, and MagSafe charging case.",
        "metadata": {
            "brand": "Apple",
            "product": "earbuds",
            "feature": "noise cancelling,wireless",
            "color": "white",
            "price": 249.00,
            "rating": 4.9,
            "category": "electronics",
        },
    },
    {
        "id": "p015",
        "description": "Samsung Galaxy Buds2 Pro true wireless earbuds with intelligent ANC, 360-degree audio, and IPX7 water resistance.",
        "metadata": {
            "brand": "Samsung",
            "product": "earbuds",
            "feature": "noise cancelling,wireless,waterproof",
            "color": "graphite",
            "price": 199.99,
            "rating": 4.5,
            "category": "electronics",
        },
    },
    {
        "id": "p016",
        "description": "Sony WF-1000XM4 true wireless earbuds with best-in-class noise cancellation, LDAC hi-res audio, and IPX4 splash resistance — in black.",
        "metadata": {
            "brand": "Sony",
            "product": "earbuds",
            "feature": "noise cancelling,wireless,hi-res audio",
            "color": "black",
            "price": 278.00,
            "rating": 4.7,
            "category": "electronics",
        },
    },
    {
        "id": "p017",
        "description": "Sony WF-1000XM5 true wireless earbuds with next-generation noise cancellation, LDAC hi-res audio, and crystal-clear call quality — in silver.",
        "metadata": {
            "brand": "Sony",
            "product": "earbuds",
            "feature": "noise cancelling,wireless,hi-res audio",
            "color": "silver",
            "price": 299.99,
            "rating": 4.8,
            "category": "electronics",
        },
    },
    {
        "id": "p018",
        "description": "Sony LinkBuds S truly wireless noise cancelling earbuds with ultra-compact design, LDAC hi-res audio, and all-day comfort — in white.",
        "metadata": {
            "brand": "Sony",
            "product": "earbuds",
            "feature": "noise cancelling,wireless,hi-res audio,compact",
            "color": "white",
            "price": 148.00,
            "rating": 4.5,
            "category": "electronics",
        },
    },
    {
        "id": "p019",
        "description": "Jabra Elite 4 active noise cancelling true wireless earbuds with IP57 rating, 28-hour total battery, and multipoint connection.",
        "metadata": {
            "brand": "Jabra",
            "product": "earbuds",
            "feature": "noise cancelling,wireless,waterproof",
            "color": "navy",
            "price": 89.99,
            "rating": 4.4,
            "category": "electronics",
        },
    },
    {
        "id": "p020",
        "description": "Soundcore Liberty 4 NC true wireless earbuds with 98.5% noise cancellation, LDAC hi-res audio, and 50-hour total battery — in white.",
        "metadata": {
            "brand": "Anker",
            "product": "earbuds",
            "feature": "noise cancelling,wireless,hi-res audio",
            "color": "white",
            "price": 79.99,
            "rating": 4.5,
            "category": "electronics",
        },
    },
    # ── Laptops ───────────────────────────────────────────────────────────────
    {
        "id": "p021",
        "description": "Apple MacBook Air M3 13-inch ultralight laptop with 18-hour battery, Liquid Retina display, and silent fanless design.",
        "metadata": {
            "brand": "Apple",
            "product": "laptop",
            "feature": "lightweight,long battery,fanless",
            "color": "silver",
            "price": 1099.00,
            "rating": 4.9,
            "category": "computers",
        },
    },
    {
        "id": "p022",
        "description": "Dell XPS 15 OLED laptop with Intel Core i9, 32GB RAM, 1TB SSD, and a 3.5K OLED touch display for creators.",
        "metadata": {
            "brand": "Dell",
            "product": "laptop",
            "feature": "OLED display,high performance,creator",
            "color": "black",
            "price": 2199.00,
            "rating": 4.7,
            "category": "computers",
        },
    },
    {
        "id": "p023",
        "description": "Acer Aspire 3 budget laptop with AMD Ryzen 5, 8GB RAM, 512GB SSD — great everyday performance at an accessible price.",
        "metadata": {
            "brand": "Acer",
            "product": "laptop",
            "feature": "budget,everyday use",
            "color": "silver",
            "price": 399.99,
            "rating": 4.2,
            "category": "computers",
        },
    },
    {
        "id": "p024",
        "description": "HP 15 budget laptop with Intel Core i5, 8GB RAM, 256GB SSD, and Windows 11 — reliable and affordable for students.",
        "metadata": {
            "brand": "HP",
            "product": "laptop",
            "feature": "budget,student,everyday use",
            "color": "silver",
            "price": 449.00,
            "rating": 4.1,
            "category": "computers",
        },
    },
    {
        "id": "p025",
        "description": "Lenovo IdeaPad 3 budget laptop with AMD Ryzen 3, 8GB RAM, and 15.6-inch FHD display — a no-frills daily driver.",
        "metadata": {
            "brand": "Lenovo",
            "product": "laptop",
            "feature": "budget,everyday use",
            "color": "grey",
            "price": 369.00,
            "rating": 4.0,
            "category": "computers",
        },
    },
    {
        "id": "p026",
        "description": "ASUS VivoBook 15 slim laptop with Intel Core i3, 8GB RAM, 512GB SSD, and fingerprint reader — lightweight and budget-friendly.",
        "metadata": {
            "brand": "ASUS",
            "product": "laptop",
            "feature": "budget,lightweight,everyday use",
            "color": "black",
            "price": 429.99,
            "rating": 4.2,
            "category": "computers",
        },
    },
    {
        "id": "p027",
        "description": "Microsoft Surface Laptop 5 with Intel Evo i5, 8GB RAM, 512GB SSD, and 13.5-inch PixelSense touchscreen — in platinum.",
        "metadata": {
            "brand": "Microsoft",
            "product": "laptop",
            "feature": "lightweight,touchscreen,premium",
            "color": "silver",
            "price": 999.99,
            "rating": 4.6,
            "category": "computers",
        },
    },
    {
        "id": "p028",
        "description": "ASUS ROG Zephyrus G14 gaming laptop with AMD Ryzen 9, RTX 4060, 16GB RAM, and 120Hz 1440p display — compact powerhouse.",
        "metadata": {
            "brand": "ASUS",
            "product": "laptop",
            "feature": "gaming,high performance,compact",
            "color": "white",
            "price": 1449.99,
            "rating": 4.8,
            "category": "computers",
        },
    },
    # ── Running shoes ─────────────────────────────────────────────────────────
    {
        "id": "p029",
        "description": "Nike Pegasus 41 road running shoes with ReactX foam cushioning, breathable mesh upper, and durable rubber outsole — in blue.",
        "metadata": {
            "brand": "Nike",
            "product": "running shoes",
            "feature": "cushioned,road running,breathable",
            "color": "blue",
            "price": 134.99,
            "rating": 4.6,
            "category": "footwear",
        },
    },
    {
        "id": "p030",
        "description": "Nike Air Zoom Pegasus 40 running shoes — trusted daily trainer with Zoom Air cushioning and engineered mesh upper — in black.",
        "metadata": {
            "brand": "Nike",
            "product": "running shoes",
            "feature": "cushioned,road running,zoom air",
            "color": "black",
            "price": 129.99,
            "rating": 4.5,
            "category": "footwear",
        },
    },
    {
        "id": "p031",
        "description": "Nike React Infinity Run Flyknit 4 running shoes designed to reduce injury, with extra cushioning and a stable ride — in white.",
        "metadata": {
            "brand": "Nike",
            "product": "running shoes",
            "feature": "cushioned,road running,injury prevention",
            "color": "white",
            "price": 159.99,
            "rating": 4.7,
            "category": "footwear",
        },
    },
    {
        "id": "p032",
        "description": "Nike Free RN 5.0 Next Nature flexible everyday running shoes with lightweight knit upper and natural motion feel — in blue.",
        "metadata": {
            "brand": "Nike",
            "product": "running shoes",
            "feature": "lightweight,road running,flexible",
            "color": "blue",
            "price": 89.99,
            "rating": 4.3,
            "category": "footwear",
        },
    },
    {
        "id": "p033",
        "description": "ASICS Gel-Nimbus 26 premium running shoes with maximum cushioning, gel technology, and wide toe box for long-distance comfort.",
        "metadata": {
            "brand": "ASICS",
            "product": "running shoes",
            "feature": "cushioned,road running,wide fit",
            "color": "white",
            "price": 159.95,
            "rating": 4.8,
            "category": "footwear",
        },
    },
    {
        "id": "p034",
        "description": "Adidas Ultraboost 24 running shoes with responsive Boost midsole, Primeknit upper, and Continental rubber outsole — in black.",
        "metadata": {
            "brand": "Adidas",
            "product": "running shoes",
            "feature": "cushioned,road running,responsive",
            "color": "black",
            "price": 189.99,
            "rating": 4.7,
            "category": "footwear",
        },
    },
    {
        "id": "p035",
        "description": "New Balance Fresh Foam X 1080v13 premium daily running shoes with ultra-cushioned midsole and engineered mesh upper — in blue.",
        "metadata": {
            "brand": "New Balance",
            "product": "running shoes",
            "feature": "cushioned,road running,premium",
            "color": "blue",
            "price": 164.99,
            "rating": 4.8,
            "category": "footwear",
        },
    },
    {
        "id": "p036",
        "description": "Hoka Clifton 9 everyday running shoes with signature thick midsole, lightweight upper, and Meta-Rocker geometry for a smooth ride.",
        "metadata": {
            "brand": "Hoka",
            "product": "running shoes",
            "feature": "cushioned,road running,lightweight",
            "color": "white",
            "price": 144.95,
            "rating": 4.8,
            "category": "footwear",
        },
    },
    # ── Smartwatches ──────────────────────────────────────────────────────────
    {
        "id": "p037",
        "description": "Apple Watch Series 9 with always-on Retina display, double tap gesture, ECG, crash detection, and 18-hour battery — in midnight.",
        "metadata": {
            "brand": "Apple",
            "product": "smartwatch",
            "feature": "ECG,crash detection,fitness tracking",
            "color": "black",
            "price": 399.00,
            "rating": 4.8,
            "category": "wearables",
        },
    },
    {
        "id": "p038",
        "description": "Samsung Galaxy Watch 6 with advanced sleep coaching, heart rate tracking, body composition analysis, and a sleek circular design.",
        "metadata": {
            "brand": "Samsung",
            "product": "smartwatch",
            "feature": "sleep tracking,fitness tracking,health monitoring",
            "color": "silver",
            "price": 299.99,
            "rating": 4.5,
            "category": "wearables",
        },
    },
    {
        "id": "p039",
        "description": "Garmin Forerunner 265 GPS running smartwatch with AMOLED display, training readiness score, and up to 15 days battery life.",
        "metadata": {
            "brand": "Garmin",
            "product": "smartwatch",
            "feature": "GPS,running,long battery,fitness tracking",
            "color": "black",
            "price": 449.99,
            "rating": 4.7,
            "category": "wearables",
        },
    },
    {
        "id": "p040",
        "description": "Fitbit Versa 4 fitness smartwatch with built-in GPS, 6-day battery, 40+ exercise modes, and Daily Readiness Score — in pink.",
        "metadata": {
            "brand": "Fitbit",
            "product": "smartwatch",
            "feature": "GPS,fitness tracking,long battery",
            "color": "pink",
            "price": 199.95,
            "rating": 4.3,
            "category": "wearables",
        },
    },
    # ── MORE Headphones ───────────────────────────────────────────────────────
    {
        "id": "p041",
        "description": "Sony WH-XB910N extra bass wireless noise cancelling headphones with 30-hour battery and multipoint connection — in blue.",
        "metadata": {
            "brand": "Sony",
            "product": "headphones",
            "feature": "noise cancelling,wireless,extra bass",
            "color": "blue",
            "price": 148.00,
            "rating": 4.4,
            "category": "electronics",
        },
    },
    {
        "id": "p042",
        "description": "Philips H9505 wireless over-ear headphones with active noise cancellation, 35-hour battery, and plush memory foam ear cushions — in white.",
        "metadata": {
            "brand": "Philips",
            "product": "headphones",
            "feature": "noise cancelling,wireless,comfortable",
            "color": "white",
            "price": 129.99,
            "rating": 4.3,
            "category": "electronics",
        },
    },
    {
        "id": "p043",
        "description": "Philips H9505 wireless noise cancelling headphones with 35-hour battery and memory foam cushions — in navy blue.",
        "metadata": {
            "brand": "Philips",
            "product": "headphones",
            "feature": "noise cancelling,wireless,comfortable",
            "color": "blue",
            "price": 129.99,
            "rating": 4.3,
            "category": "electronics",
        },
    },
    {
        "id": "p044",
        "description": "Edifier WH950NB wireless active noise cancelling headphones with LDAC hi-res audio, 55-hour battery, and premium build — in white.",
        "metadata": {
            "brand": "Edifier",
            "product": "headphones",
            "feature": "noise cancelling,wireless,hi-res audio",
            "color": "white",
            "price": 99.99,
            "rating": 4.5,
            "category": "electronics",
        },
    },
    {
        "id": "p045",
        "description": "Edifier WH950NB wireless active noise cancelling headphones with LDAC hi-res audio and 55-hour playtime — in black.",
        "metadata": {
            "brand": "Edifier",
            "product": "headphones",
            "feature": "noise cancelling,wireless,hi-res audio",
            "color": "black",
            "price": 99.99,
            "rating": 4.5,
            "category": "electronics",
        },
    },
    {
        "id": "p046",
        "description": "Skullcandy Crusher ANC 2 wireless headphones with sensory bass, personal sound, and 50-hour battery — in white.",
        "metadata": {
            "brand": "Skullcandy",
            "product": "headphones",
            "feature": "noise cancelling,wireless,bass",
            "color": "white",
            "price": 149.99,
            "rating": 4.2,
            "category": "electronics",
        },
    },
    {
        "id": "p047",
        "description": "Anker Soundcore Space One active noise cancelling headphones with 40-hour battery and foldable design — in white.",
        "metadata": {
            "brand": "Anker",
            "product": "headphones",
            "feature": "noise cancelling,wireless,foldable",
            "color": "white",
            "price": 79.99,
            "rating": 4.4,
            "category": "electronics",
        },
    },
    {
        "id": "p048",
        "description": "Anker Soundcore Space One active noise cancelling headphones with 40-hour battery and foldable design — in blue.",
        "metadata": {
            "brand": "Anker",
            "product": "headphones",
            "feature": "noise cancelling,wireless,foldable",
            "color": "blue",
            "price": 79.99,
            "rating": 4.4,
            "category": "electronics",
        },
    },
    {
        "id": "p049",
        "description": "Jabra Evolve2 55 professional wireless ANC headphones with 3-mic call technology, 49-hour battery, and flexible wearing styles — in beige.",
        "metadata": {
            "brand": "Jabra",
            "product": "headphones",
            "feature": "noise cancelling,wireless,professional",
            "color": "beige",
            "price": 299.00,
            "rating": 4.5,
            "category": "electronics",
        },
    },
    {
        "id": "p050",
        "description": "1MORE SonoFlow SE wireless noise cancelling headphones with LDAC hi-res audio and 70-hour battery — exceptional value in white.",
        "metadata": {
            "brand": "1MORE",
            "product": "headphones",
            "feature": "noise cancelling,wireless,hi-res audio",
            "color": "white",
            "price": 59.99,
            "rating": 4.4,
            "category": "electronics",
        },
    },
    {
        "id": "p051",
        "description": "1MORE SonoFlow SE wireless noise cancelling headphones with LDAC hi-res audio and 70-hour battery — in black.",
        "metadata": {
            "brand": "1MORE",
            "product": "headphones",
            "feature": "noise cancelling,wireless,hi-res audio",
            "color": "black",
            "price": 59.99,
            "rating": 4.4,
            "category": "electronics",
        },
    },
    # ── MORE Earbuds ──────────────────────────────────────────────────────────
    {
        "id": "p052",
        "description": "Google Pixel Buds Pro 2 true wireless earbuds with active noise cancellation, Gemini AI integration, and 8-hour playtime — in porcelain white.",
        "metadata": {
            "brand": "Google",
            "product": "earbuds",
            "feature": "noise cancelling,wireless,AI assistant",
            "color": "white",
            "price": 229.00,
            "rating": 4.6,
            "category": "electronics",
        },
    },
    {
        "id": "p053",
        "description": "Bose QuietComfort Ultra Earbuds with immersive audio, world-class ANC, and CustomTune personalization — in white.",
        "metadata": {
            "brand": "Bose",
            "product": "earbuds",
            "feature": "noise cancelling,wireless,immersive audio",
            "color": "white",
            "price": 299.00,
            "rating": 4.7,
            "category": "electronics",
        },
    },
    {
        "id": "p054",
        "description": "Bose QuietComfort Earbuds II with personalized ANC, CustomTune sound calibration, and 6-hour battery — in black.",
        "metadata": {
            "brand": "Bose",
            "product": "earbuds",
            "feature": "noise cancelling,wireless",
            "color": "black",
            "price": 249.00,
            "rating": 4.6,
            "category": "electronics",
        },
    },
    {
        "id": "p055",
        "description": "Technics EAH-AZ80 premium true wireless earbuds with multipoint Bluetooth, LDAC hi-res audio, and 3D surround sound — in black.",
        "metadata": {
            "brand": "Technics",
            "product": "earbuds",
            "feature": "noise cancelling,wireless,hi-res audio",
            "color": "black",
            "price": 279.99,
            "rating": 4.7,
            "category": "electronics",
        },
    },
    {
        "id": "p056",
        "description": "Soundcore Liberty 4 true wireless earbuds with 3D spatial audio, LDAC hi-res, heart rate monitoring, and 28-hour total battery — in white.",
        "metadata": {
            "brand": "Anker",
            "product": "earbuds",
            "feature": "noise cancelling,wireless,hi-res audio,heart rate",
            "color": "white",
            "price": 99.99,
            "rating": 4.4,
            "category": "electronics",
        },
    },
    {
        "id": "p057",
        "description": "Nothing Ear (2) true wireless earbuds with dual active noise cancellation, LDAC hi-res audio, and distinctive transparent design — in white.",
        "metadata": {
            "brand": "Nothing",
            "product": "earbuds",
            "feature": "noise cancelling,wireless,hi-res audio",
            "color": "white",
            "price": 149.00,
            "rating": 4.5,
            "category": "electronics",
        },
    },
    {
        "id": "p058",
        "description": "Nothing Ear (a) true wireless earbuds with active noise cancellation, 42.5-hour total battery, and IP54 rating — in yellow.",
        "metadata": {
            "brand": "Nothing",
            "product": "earbuds",
            "feature": "noise cancelling,wireless,waterproof",
            "color": "yellow",
            "price": 99.00,
            "rating": 4.5,
            "category": "electronics",
        },
    },
    {
        "id": "p059",
        "description": "Edifier NeoBuds Pro 2 true wireless earbuds with LDAC hi-res audio, dual-driver setup, and strong ANC — in white.",
        "metadata": {
            "brand": "Edifier",
            "product": "earbuds",
            "feature": "noise cancelling,wireless,hi-res audio",
            "color": "white",
            "price": 89.99,
            "rating": 4.4,
            "category": "electronics",
        },
    },
    # ── MORE Laptops ──────────────────────────────────────────────────────────
    {
        "id": "p060",
        "description": "Lenovo ThinkPad E14 Gen 5 business laptop with AMD Ryzen 7, 16GB RAM, 512GB SSD, and MIL-SPEC durability — in black.",
        "metadata": {
            "brand": "Lenovo",
            "product": "laptop",
            "feature": "business,durable,everyday use",
            "color": "black",
            "price": 749.00,
            "rating": 4.5,
            "category": "computers",
        },
    },
    {
        "id": "p061",
        "description": "HP Pavilion 15 budget laptop with Intel Core i7, 16GB RAM, 512GB SSD, and a full HD IPS display — a capable everyday machine.",
        "metadata": {
            "brand": "HP",
            "product": "laptop",
            "feature": "budget,everyday use,student",
            "color": "silver",
            "price": 479.99,
            "rating": 4.3,
            "category": "computers",
        },
    },
    {
        "id": "p062",
        "description": "Acer Swift 3 slim laptop with Intel Core i5, 8GB RAM, 512GB SSD, and 10-hour battery — a reliable lightweight budget pick.",
        "metadata": {
            "brand": "Acer",
            "product": "laptop",
            "feature": "budget,lightweight,long battery",
            "color": "silver",
            "price": 449.99,
            "rating": 4.3,
            "category": "computers",
        },
    },
    {
        "id": "p063",
        "description": "Samsung Galaxy Book4 laptop with Intel Core 5, 16GB RAM, 256GB SSD, and a slim design that pairs with Galaxy devices seamlessly.",
        "metadata": {
            "brand": "Samsung",
            "product": "laptop",
            "feature": "lightweight,everyday use,premium",
            "color": "silver",
            "price": 699.99,
            "rating": 4.4,
            "category": "computers",
        },
    },
    {
        "id": "p064",
        "description": "Lenovo Yoga 7i 2-in-1 laptop with Intel Core i7, 16GB RAM, OLED touchscreen, and 360-degree hinge — premium versatility.",
        "metadata": {
            "brand": "Lenovo",
            "product": "laptop",
            "feature": "2-in-1,touchscreen,OLED display,premium",
            "color": "grey",
            "price": 849.99,
            "rating": 4.6,
            "category": "computers",
        },
    },
    {
        "id": "p065",
        "description": "HP Chromebook 15 budget laptop with Intel Celeron, 4GB RAM, 64GB eMMC, and ChromeOS — lightweight web browsing on a tight budget.",
        "metadata": {
            "brand": "HP",
            "product": "laptop",
            "feature": "budget,lightweight,chromeos",
            "color": "silver",
            "price": 299.00,
            "rating": 4.0,
            "category": "computers",
        },
    },
    {
        "id": "p066",
        "description": "Acer Chromebook Spin 714 convertible laptop with Intel Core i5, 8GB RAM, 256GB SSD, and military-grade durability — a solid budget 2-in-1.",
        "metadata": {
            "brand": "Acer",
            "product": "laptop",
            "feature": "budget,2-in-1,durable,chromeos",
            "color": "grey",
            "price": 399.00,
            "rating": 4.3,
            "category": "computers",
        },
    },
    {
        "id": "p067",
        "description": "MSI Thin 15 gaming laptop with Intel Core i7, RTX 4050, 16GB RAM, 144Hz display — gaming performance without breaking the bank.",
        "metadata": {
            "brand": "MSI",
            "product": "laptop",
            "feature": "gaming,high performance",
            "color": "black",
            "price": 899.99,
            "rating": 4.5,
            "category": "computers",
        },
    },
    {
        "id": "p068",
        "description": "Apple MacBook Pro M3 14-inch with ProRes video, 18GB unified memory, and 22-hour battery — the professional creative's workhorse.",
        "metadata": {
            "brand": "Apple",
            "product": "laptop",
            "feature": "high performance,creator,long battery",
            "color": "silver",
            "price": 1599.00,
            "rating": 4.9,
            "category": "computers",
        },
    },
    # ── MORE Running shoes ────────────────────────────────────────────────────
    {
        "id": "p069",
        "description": "Nike Vomero 17 max-cushion running shoes with thick ZoomX foam and plush upper for premium long-run comfort — in white.",
        "metadata": {
            "brand": "Nike",
            "product": "running shoes",
            "feature": "cushioned,road running,max cushion",
            "color": "white",
            "price": 164.99,
            "rating": 4.7,
            "category": "footwear",
        },
    },
    {
        "id": "p070",
        "description": "Nike Winflo 11 everyday running shoes with lightweight foam and engineered mesh upper — an affordable daily trainer in blue.",
        "metadata": {
            "brand": "Nike",
            "product": "running shoes",
            "feature": "lightweight,road running,everyday",
            "color": "blue",
            "price": 89.99,
            "rating": 4.3,
            "category": "footwear",
        },
    },
    {
        "id": "p071",
        "description": "Nike Revolution 7 budget road running shoes with lightweight foam and classic fit — a no-fuss daily trainer in white.",
        "metadata": {
            "brand": "Nike",
            "product": "running shoes",
            "feature": "budget,road running,lightweight",
            "color": "white",
            "price": 64.99,
            "rating": 4.2,
            "category": "footwear",
        },
    },
    {
        "id": "p072",
        "description": "Nike Revolution 7 budget running shoes — same great everyday trainer, available in blue.",
        "metadata": {
            "brand": "Nike",
            "product": "running shoes",
            "feature": "budget,road running,lightweight",
            "color": "blue",
            "price": 64.99,
            "rating": 4.2,
            "category": "footwear",
        },
    },
    {
        "id": "p073",
        "description": "ASICS Gel-Kayano 31 premium stability running shoes with maximum cushioning and a supportive platform for long-distance runners.",
        "metadata": {
            "brand": "ASICS",
            "product": "running shoes",
            "feature": "cushioned,stability,road running",
            "color": "blue",
            "price": 159.95,
            "rating": 4.7,
            "category": "footwear",
        },
    },
    {
        "id": "p074",
        "description": "Saucony Endorphin Speed 4 running shoes with nylon SpeedRoll plate and PWRRUN PB foam — a fast trainer for race days in white.",
        "metadata": {
            "brand": "Saucony",
            "product": "running shoes",
            "feature": "racing,road running,responsive",
            "color": "white",
            "price": 169.99,
            "rating": 4.8,
            "category": "footwear",
        },
    },
    {
        "id": "p075",
        "description": "Brooks Ghost 16 neutral everyday running shoes with DNA Loft v3 cushioning and smooth ride — a trusted long-distance companion in blue.",
        "metadata": {
            "brand": "Brooks",
            "product": "running shoes",
            "feature": "cushioned,road running,neutral",
            "color": "blue",
            "price": 139.95,
            "rating": 4.7,
            "category": "footwear",
        },
    },
    {
        "id": "p076",
        "description": "On Cloudmonster 2 max-cushion road running shoes with dual-density CloudTec sole and energetic rebound — in white.",
        "metadata": {
            "brand": "On",
            "product": "running shoes",
            "feature": "cushioned,road running,max cushion",
            "color": "white",
            "price": 169.99,
            "rating": 4.6,
            "category": "footwear",
        },
    },
    {
        "id": "p077",
        "description": "Puma Velocity Nitro 3 lightweight daily running shoes with NITRO foam midsole and mesh upper — a peppy trainer in blue.",
        "metadata": {
            "brand": "Puma",
            "product": "running shoes",
            "feature": "lightweight,road running,responsive",
            "color": "blue",
            "price": 119.99,
            "rating": 4.4,
            "category": "footwear",
        },
    },
    # ── Phones ────────────────────────────────────────────────────────────────
    {
        "id": "p078",
        "description": "Apple iPhone 16 Pro with A18 Pro chip, titanium design, 48MP camera system, and 4K 120fps video recording — in black titanium.",
        "metadata": {
            "brand": "Apple",
            "product": "smartphone",
            "feature": "5G,pro camera,titanium",
            "color": "black",
            "price": 999.00,
            "rating": 4.8,
            "category": "phones",
        },
    },
    {
        "id": "p079",
        "description": "Apple iPhone 16 with A18 chip, improved camera with optical zoom, and Action button — in white.",
        "metadata": {
            "brand": "Apple",
            "product": "smartphone",
            "feature": "5G,camera,Action button",
            "color": "white",
            "price": 799.00,
            "rating": 4.7,
            "category": "phones",
        },
    },
    {
        "id": "p080",
        "description": "Samsung Galaxy S25 with Snapdragon 8 Elite, 50MP camera, 7 years of updates, and slim titanium frame — in violet.",
        "metadata": {
            "brand": "Samsung",
            "product": "smartphone",
            "feature": "5G,pro camera,AI features",
            "color": "violet",
            "price": 799.99,
            "rating": 4.7,
            "category": "phones",
        },
    },
    {
        "id": "p081",
        "description": "Google Pixel 9 with Google Tensor G4, 50MP camera, 7 years of updates, and built-in Gemini AI — in hazel.",
        "metadata": {
            "brand": "Google",
            "product": "smartphone",
            "feature": "5G,pro camera,AI features",
            "color": "hazel",
            "price": 799.00,
            "rating": 4.6,
            "category": "phones",
        },
    },
    {
        "id": "p082",
        "description": "Nothing Phone (2a) mid-range smartphone with Dimensity 7200 Pro, Glyph Interface lighting, and clean Nothing OS — in black.",
        "metadata": {
            "brand": "Nothing",
            "product": "smartphone",
            "feature": "5G,clean software,unique design",
            "color": "black",
            "price": 349.00,
            "rating": 4.4,
            "category": "phones",
        },
    },
    {
        "id": "p083",
        "description": "OnePlus 12 flagship smartphone with Hasselblad camera, 100W fast charging, Snapdragon 8 Gen 3, and 6.82-inch 120Hz display — in black.",
        "metadata": {
            "brand": "OnePlus",
            "product": "smartphone",
            "feature": "5G,fast charging,pro camera",
            "color": "black",
            "price": 799.00,
            "rating": 4.6,
            "category": "phones",
        },
    },
    # ── Tablets ───────────────────────────────────────────────────────────────
    {
        "id": "p084",
        "description": "Apple iPad Air M2 11-inch with M2 chip, stunning Liquid Retina display, Apple Pencil Pro support, and 10-hour battery — in blue.",
        "metadata": {
            "brand": "Apple",
            "product": "tablet",
            "feature": "lightweight,long battery,stylus support",
            "color": "blue",
            "price": 599.00,
            "rating": 4.8,
            "category": "computers",
        },
    },
    {
        "id": "p085",
        "description": "Samsung Galaxy Tab S9 FE with 10.9-inch display, IP68 rating, S Pen included, and 8000mAh battery — in grey.",
        "metadata": {
            "brand": "Samsung",
            "product": "tablet",
            "feature": "stylus support,waterproof,long battery",
            "color": "grey",
            "price": 449.99,
            "rating": 4.5,
            "category": "computers",
        },
    },
    # ── Mechanical keyboards ──────────────────────────────────────────────────
    {
        "id": "p086",
        "description": "Keychron Q3 Pro full-size wireless mechanical keyboard with hot-swappable sockets, gasket mount, and stunning RGB — in black.",
        "metadata": {
            "brand": "Keychron",
            "product": "mechanical keyboard",
            "feature": "wireless,hot-swappable,RGB,gasket mount",
            "color": "black",
            "price": 169.99,
            "rating": 4.8,
            "category": "peripherals",
        },
    },
    {
        "id": "p087",
        "description": "Nuphy Air75 V2 ultra-slim wireless mechanical keyboard with low-profile switches, 75% layout, and RGB — in white.",
        "metadata": {
            "brand": "Nuphy",
            "product": "mechanical keyboard",
            "feature": "wireless,slim,RGB,compact",
            "color": "white",
            "price": 109.99,
            "rating": 4.6,
            "category": "peripherals",
        },
    },
    {
        "id": "p088",
        "description": "Royal Kludge RK68 compact 65% wireless mechanical keyboard with tri-mode connectivity and RGB backlight — in white.",
        "metadata": {
            "brand": "Royal Kludge",
            "product": "mechanical keyboard",
            "feature": "wireless,compact,RGB",
            "color": "white",
            "price": 49.99,
            "rating": 4.3,
            "category": "peripherals",
        },
    },
    # ── Monitors ──────────────────────────────────────────────────────────────
    {
        "id": "p089",
        "description": "LG 27GP950-B 27-inch 4K Nano IPS gaming monitor with 160Hz, 1ms, HDMI 2.1, and NVIDIA G-SYNC Compatible.",
        "metadata": {
            "brand": "LG",
            "product": "monitor",
            "feature": "4K,gaming,144Hz+,G-Sync",
            "color": "black",
            "price": 699.99,
            "rating": 4.7,
            "category": "computers",
        },
    },
    {
        "id": "p090",
        "description": "Dell S2722DGM curved gaming monitor with 27-inch QHD 165Hz VA panel, AMD FreeSync Premium, and immersive curved design.",
        "metadata": {
            "brand": "Dell",
            "product": "monitor",
            "feature": "gaming,curved,165Hz,FreeSync",
            "color": "black",
            "price": 249.99,
            "rating": 4.5,
            "category": "computers",
        },
    },
    {
        "id": "p091",
        "description": "BenQ PD2706UA 27-inch 4K USB-C monitor with factory-calibrated color, Thunderbolt 4 hub, and IPS Black panel — for designers.",
        "metadata": {
            "brand": "BenQ",
            "product": "monitor",
            "feature": "4K,USB-C,color accurate,Thunderbolt",
            "color": "black",
            "price": 849.99,
            "rating": 4.7,
            "category": "computers",
        },
    },
    # ── Cameras ───────────────────────────────────────────────────────────────
    {
        "id": "p092",
        "description": "Sony ZV-E10 II APS-C mirrorless camera with 26MP sensor, 4K video, real-time eye autofocus, and vlog-friendly flip screen — in black.",
        "metadata": {
            "brand": "Sony",
            "product": "camera",
            "feature": "mirrorless,4K video,autofocus,vlogging",
            "color": "black",
            "price": 749.99,
            "rating": 4.7,
            "category": "cameras",
        },
    },
    {
        "id": "p093",
        "description": "Canon EOS R50 compact mirrorless camera with 24MP sensor, 4K video, Dual Pixel CMOS AF, and beginner-friendly automatic modes — in white.",
        "metadata": {
            "brand": "Canon",
            "product": "camera",
            "feature": "mirrorless,4K video,autofocus,beginner",
            "color": "white",
            "price": 679.99,
            "rating": 4.6,
            "category": "cameras",
        },
    },
    {
        "id": "p094",
        "description": "Fujifilm X-T50 mirrorless camera with 40MP sensor, film simulation modes, in-body image stabilization, and retro design — in silver.",
        "metadata": {
            "brand": "Fujifilm",
            "product": "camera",
            "feature": "mirrorless,film simulation,IBIS,retro",
            "color": "silver",
            "price": 1299.99,
            "rating": 4.8,
            "category": "cameras",
        },
    },
    # ── Gaming ────────────────────────────────────────────────────────────────
    {
        "id": "p095",
        "description": "Sony PlayStation 5 Slim console with disc drive, 1TB SSD, DualSense controller, and 4K gaming support — in white.",
        "metadata": {
            "brand": "Sony",
            "product": "gaming console",
            "feature": "4K gaming,SSD,disc drive",
            "color": "white",
            "price": 449.99,
            "rating": 4.8,
            "category": "gaming",
        },
    },
    {
        "id": "p096",
        "description": "Microsoft Xbox Series X 1TB console with 4K 120fps gaming, Quick Resume, and full backward compatibility — in black.",
        "metadata": {
            "brand": "Microsoft",
            "product": "gaming console",
            "feature": "4K gaming,SSD,backward compatible",
            "color": "black",
            "price": 499.99,
            "rating": 4.7,
            "category": "gaming",
        },
    },
    {
        "id": "p097",
        "description": "Nintendo Switch OLED handheld console with 7-inch OLED screen, 64GB storage, and enhanced audio — in white.",
        "metadata": {
            "brand": "Nintendo",
            "product": "gaming console",
            "feature": "handheld,OLED,portable",
            "color": "white",
            "price": 349.99,
            "rating": 4.8,
            "category": "gaming",
        },
    },
]
